In [1]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.20.0


### Load Dataset

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

scaled the values to a range of (0,1) and converts sample data from int to float

In [3]:
model = tf.keras.Sequential([
    tf.keras.Input(shape=(28,28)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.2829494 , -0.13421054, -0.3155354 , -0.18582799, -0.54121053,
         0.4866125 , -0.16109961,  0.5210295 ,  0.31622407,  0.14263482]],
      dtype=float32)

In [15]:
tf.nn.softmax(predictions).numpy()

array([[0.09110503, 0.06723826, 0.25206485, 0.06603651, 0.16261749,
        0.05918432, 0.07543631, 0.096622  , 0.07488381, 0.05481147]],
      dtype=float32)

In [15]:
tf.nn.softmax(predictions).numpy()

array([[0.09110503, 0.06723826, 0.25206485, 0.06603651, 0.16261749,
        0.05918432, 0.07543631, 0.096622  , 0.07488381, 0.05481147]],
      dtype=float32)

### Loss function

In [16]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [17]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.8270986)

In [18]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

### Fit

In [21]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9788 - loss: 0.0669
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9810 - loss: 0.0592
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9818 - loss: 0.0561
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9843 - loss: 0.0479
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9852 - loss: 0.0453


### Evaluation

In [22]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9811 - loss: 0.0670


[0.06704398989677429, 0.9811000227928162]

In [24]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [25]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.4881015e-10, 7.1725244e-09, 2.4748906e-06, 4.3650471e-05,
        2.6902143e-13, 5.1125237e-10, 6.4828916e-16, 9.9995387e-01,
        3.9417425e-09, 4.0179710e-08],
       [2.2285807e-11, 2.5338622e-07, 9.9999976e-01, 4.3731990e-10,
        5.0361822e-25, 7.8989731e-10, 7.5289844e-12, 1.1124001e-18,
        1.2153893e-11, 3.1158305e-18],
       [9.6514596e-10, 9.9991369e-01, 4.4716530e-06, 1.2954633e-08,
        3.6174135e-06, 2.4473865e-08, 6.3092898e-08, 7.5284843e-05,
        2.8678417e-06, 2.6218476e-09],
       [9.9996221e-01, 1.0259951e-09, 2.7482938e-05, 2.1696687e-08,
        5.0277931e-11, 3.7166352e-08, 5.2782963e-07, 3.6517958e-09,
        3.7670693e-09, 9.7243837e-06],
       [1.3296275e-06, 3.3875455e-13, 3.5058285e-08, 1.1980983e-10,
        9.9935573e-01, 1.2047747e-08, 1.5681633e-07, 8.0058426e-06,
        2.4277415e-07, 6.3444843e-04]], dtype=float32)>