In [2]:
import tensorflow as tf

a = tf.constant(5)
b = tf.constant([1,2,3])
c = tf.constant([[1,2], [3,4]])

print(a)
print(b)
print(c)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [3]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Tensor:", x)
print("Rank:", tf.rank(x))        
print("Shape:", x.shape)        
print("Dtype:", x.dtype)

Tensor: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Rank: tf.Tensor(2, shape=(), dtype=int32)
Shape: (2, 3)
Dtype: <dtype: 'int32'>


### Special Tensors

In [4]:
zeros = tf.zeros((2,3))
ones = tf.ones((3,3))
random_tensor = tf.random.normal((2,2), mean=0, stddev=1)

print(zeros)
print(ones)
print(random_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-1.663508    0.0510742 ]
 [-0.10738381 -0.19758226]], shape=(2, 2), dtype=float32)


### Operations

#### Element wise operations

In [6]:
x = tf.constant([2, 4, 6])
y = tf.constant([1, 1, 1])

print('Add:', x+y)
print('Multiply:', x*y)
print('Square:', tf.square(x))

Add: tf.Tensor([3 5 7], shape=(3,), dtype=int32)
Multiply: tf.Tensor([2 4 6], shape=(3,), dtype=int32)
Square: tf.Tensor([ 4 16 36], shape=(3,), dtype=int32)


#### Matrix Multiplication

In [10]:
a = tf.constant([[1, 2, 3]])
b = tf.constant([[4], [5], [6]])

print(a.shape, b.shape)

c = tf.matmul(a,b)
print('Matrix Multiplication Result:', c)

(1, 3) (3, 1)
Matrix Multiplication Result: tf.Tensor([[32]], shape=(1, 1), dtype=int32)


#### Broadcasting

In [21]:
a = tf.constant([[1, 2, 3]])
b = tf.constant(2)

print(a+b)


tf.Tensor([[3 4 5]], shape=(1, 3), dtype=int32)


In [22]:
a = tf.constant([[1, 2, 3],[4, 5, 6]])
b = tf.constant([10, 20, 30])

print(a+b)

tf.Tensor(
[[11 22 33]
 [14 25 36]], shape=(2, 3), dtype=int32)


In [24]:
a = tf.constant([[1],
                 [2],
                 [3]])
b = tf.constant([10, 20, 30])

print(a + b)

tf.Tensor(
[[11 21 31]
 [12 22 32]
 [13 23 33]], shape=(3, 3), dtype=int32)


In [26]:
a = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]]) 
b = tf.constant([10, 20, 30])  

# print(a+b) --fails

Broadcasting FAILS when any dimension pair (right → left):
- are different
- and not equal to 1
- and not missing

#### Indexing and Slicing

In [28]:
x = tf.constant([[10, 20, 30],
                 [40, 50, 60]])

print("First row:", x[0])
print("Element (1,1):", x[1, 1])
print("All rows, first two columns:\n", x[:, :2])

First row: tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Element (1,1): tf.Tensor(50, shape=(), dtype=int32)
All rows, first two columns:
 tf.Tensor(
[[10 20]
 [40 50]], shape=(2, 2), dtype=int32)


### Example: Graph Created Automatically Using tf.function

In [29]:
import tensorflow as tf

@tf.function
def compute(x):
    return tf.square(x) + tf.sin(x)

result = compute(tf.constant(3.0))
print(result)


tf.Tensor(9.14112, shape=(), dtype=float32)


### Graph in a Keras Model (TF2)

Even though you write Keras code normally, training uses a graph internally.

In [30]:
from tensorflow.keras import layers, Model

inputs = layers.Input(shape=(4,))
x = layers.Dense(8, activation="relu")(inputs)
outputs = layers.Dense(3)(x)

model = Model(inputs, outputs)
model.compile(optimizer="adam", loss="mse")

model.fit(tf.random.normal((10, 4)), tf.random.normal((10, 3)), epochs=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 778ms/step - loss: 1.0506
